version: '3.8'

services:
  # Base de données MySQL (à démarrer en premier)
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "dbuadb"  # Nom cohérent avec votre DATABASE_URL
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s

  # Service principal NestJS
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: microservice-uadb:0.0.1
    container_name: microservice-uadb
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      DATABASE_URL: "mysql://root@mysql-db:3306/dbuadb"
      JWT_SECRET: "3889c5248ae7b3254b78c22c31de58eab58cb9b9222e6fdbe7af07b878699d77"
      JWT_EXPIRES_IN: "24h"
      FRONTEND_URL: "http://localhost:3000"
    depends_on:
      mysql:
        condition: service_healthy  # Attend que MySQL soit prêt
    restart: unless-stopped
    command: sh -c "sleep 10 && npx prisma generate && npx prisma db push && npm run start:uadb"

volumes:
  mysql_data:
    driver: local
