version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "dbuadb"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: microservice-uadb:0.0.1
    container_name: microservice-uadb
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      DATABASE_URL: "mysql://root@mysql-db:3306/dbuadb"
      FRONTEND_URL: "http://localhost:3000"
      EMAIL_PROVIDER: "smtp"
      SMTP_HOST: "smtp.gmail.com"
      SMTP_PORT: 587
      SMTP_SECURE: "false"
      SMTP_USER: "syoumar505@gmail.com"
      SMTP_PASS: "qbwhfhxuxlqmrvzo"
      SMTP_TLS_REJECT_UNAUTHORIZED: "false"

    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    command: sh -c "sleep 10 && npx prisma generate && npx prisma db push && npm run start:uadb"

volumes:
  mysql_data: