-- AlterTable
ALTER TABLE `Ressource` ADD COLUMN `date_publication` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `est_archive` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `est_valide` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `image` VARCHAR(191) NULL,
    ADD COLUMN `niveau_acces` ENUM('PUBLIC', 'AUTHENTIFIE', 'UNIVERSITE_ORIGINE', 'PRIVE') NOT NULL DEFAULT 'PUBLIC';
